/**
 * Blockdoku PWA - Build Information Utility
 * Loads and provides build information including version and build identifier
 *
 * IMPORTANT: `build-info.json` is generated by `scripts/generate-build-info.js`.
 * - In normal builds, this file MUST exist. The Settings → About UI depends on it.
 * - If it's missing, we intentionally fall back to a synthesized value for
 *   development only. Do not rely on fallback in production deployments.
 */

export class BuildInfo {
    constructor() {
        this.buildInfo = null;
        this.loadBuildInfo();
    }
    
    async loadBuildInfo() {
        try {
            // Try to fetch build info from generated file
            const response = await fetch('./build-info.json');
            if (response.ok) {
                this.buildInfo = await response.json();
            } else {
                throw new Error('Build info file not found');
            }
        } catch (error) {
            console.warn('Build info not found, using fallback');
            this.buildInfo = this.getFallbackBuildInfo();
        }
    }
    
    getFallbackBuildInfo() {
        // Development fallback ONLY. This exists to keep local dev running
        // even if the generator has not been executed. Production should
        // always ship a real build-info.json generated at build time.
        const now = new Date();
        const buildId = now.toISOString().slice(0, 16).replace(/[-:T]/g, '');
        
        return {
            version: '1.6.1',
            buildId: buildId,
            buildDate: now.toISOString(),
            fullVersion: `1.6.1+${buildId}`
        };
    }
    
    getVersion() {
        return this.buildInfo?.version || '1.6.1';
    }
    
    getBuildId() {
        return this.buildInfo?.buildId || 'dev';
    }
    
    getFullVersion() {
        return this.buildInfo?.fullVersion || '1.6.1+dev';
    }
    
    getBuildDate() {
        return this.buildInfo?.buildDate || new Date().toISOString();
    }
    
    getFormattedBuildDate() {
        const date = new Date(this.getBuildDate());
        return date.toLocaleString();
    }
    
    getDisplayVersion() {
        return `v${this.getFullVersion()}`;
    }
    
    isLoaded() {
        return this.buildInfo !== null;
    }
}

// Create singleton instance
export const buildInfo = new BuildInfo();
